# Generated by Django 4.1.6 on 2023-02-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_financemodel_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financemodel',
            name='price',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financemodel',
            name='processing_and_delivery',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financemodel',
            name='sale_commission',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
