# Generated by Django 4.1.6 on 2023-02-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_financemodel_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financemodel',
            name='price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='financemodel',
            name='processing_and_delivery',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='financemodel',
            name='sale_commission',
            field=models.BigIntegerField(null=True),
        ),
    ]
