# Generated by Django 4.1.6 on 2023-02-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_financemodel_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceMonthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('current_profit', models.BigIntegerField()),
                ('expected_profit', models.BigIntegerField()),
            ],
        ),
    ]
