# Generated by Django 4.1.6 on 2023-02-10 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.DateField()),
                ('order_number', models.BigIntegerField(unique=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.marketmodel')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsmodel')),
            ],
        ),
    ]
