# Generated by Django 4.1.6 on 2023-02-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordersmodel_actually_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
