# Generated by Django 4.1.6 on 2023-02-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordersmodel_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='order_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
