# Generated by Django 4.1.6 on 2023-02-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_ordersmodel_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='is_printed',
            field=models.BooleanField(default=False),
        ),
    ]
